### ISSUE TITLE
Breaking change - 5.*.* does not appear to work with Node v6.*.*

### ISSUE THREAD

**Issue by dynamite-ready** [hapijs/inert#106]
It's definitely broken on Node v6.10.0.
Reverting to Inert 4.2.1 is fine though, so I suspect recent changes have broken the module.

**Comment by wswoodruff** [comment]
`hapi v17` is pretty much a 'new framework' with a decent amount of breaking changes @dynamite-ready -- all hapi modules are updating including breaking changes
