### ISSUE TITLE
Version Mismatch: Hapi 17.x not on NPM yet; Inert 5.x is current

### ISSUE THREAD

**Issue by mitchellst** [hapijs/inert#107]
This should be closed soon, but at the moment, running `npm install hapi inert` or `yarn add hapi inert` will yield incompatible versions of the two packages. The current version of inert on NPM requires Hapi 17, which has not been released yet. It looks like it's been this way for a few days.

Temporary workaround for anybody who has the issue is to install `inert@4`.

**Comment by WesTyler** [comment]
You should also be able to grab hapi 17 by using the `next` tag: `npm i hapi@next`

**Comment by Marsup** [comment]
Version 17 has been released, the tag "latest" isn't changed yet but that shouldn't matter.

**Comment by alexander3um** [comment]
It hasn't tho, official release should be this week, but right now it isn't.

**Comment by Marsup** [comment]
![image](https://user-images.githubusercontent.com/796194/32536297-2c720898-c45e-11e7-8ecc-682601e03d74.png)
What hasn't been released ?

**Comment by AdriVanHoudt** [comment]
It is not tagged as latest?

**Comment by Marsup** [comment]
Intentionally so.

**Comment by mitchellst** [comment]
It doesn't really matter. I mostly left this here for anyone googling / who broke their build until this is resolved. Once the latest tag is moved to hapi 17, we should close this. The solutions above all work.

Inert is in the tutorials on hapijs.com, so anybody working through those and/or using them as a reference right now will get a broken installation. It's a minor problem, but it is always best when the docs "work." Small hiccups like this are a side-effect of how actively the community maintains hapi, which is awesome. I consider it node.js for grownups, which is why I'm trying to sell the platform for a few projects at work right now. That case will be helped by minimizing these things, which is why I brought it up.

Thanks for the awesome work, maintainers.

**Comment by devinivy** [comment]
I see what you're saying and can see how it's a minor issue, esp. as it relates to tutorials, etc.  It's funny timing right now with hapi v17 actively becoming "latest".  While the ecosystem catches-up with hapi v17 you'll probably run into a handful of oddities like this, but it should settle before very long.  I suppose inert could have also held off on tagging v5 as "latest" until hapi v17 does the same.  I think it's good to note for the future– thanks.

**Comment by Marsup** [comment]
I'd still say it's not an issue on our side. Tutorials should make you install like `npm install hapi@17`, not `npm install hapi`.
npm is reporting correctly the discrepancy, I hope most people would figure out something is wrong.

**Comment by antony** [comment]
Glad this issue is here - because yes it is a little misleading right now.

**Comment by Tav0** [comment]
Thank you, this issue was driving me nuts.

**Comment by kanongil** [comment]
Closing since hapi@17 is now the default install.
