### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by graham-willis-druid** [hapijs/inert#108]
What is the plan for inert?

**Comment by graham-willis-druid** [comment]
Is there a plan to update insert to support hapi v17?

**Comment by wswoodruff** [comment]
What do you mean what's the plan? The plan is Inert is staying right here as far as I know

**Comment by wswoodruff** [comment]
Missed the title -- so used to seeing that loL
@graham-willis-druid inert `v5.x.x` supports hapi v17 =)

**Comment by graham-willis-druid** [comment]
Thanks!
