### ISSUE TITLE
Setting custom headers for the file/directory handler

### ISSUE THREAD

**Issue by aquilax** [hapijs/inert#11]
I need to change the `Cache-control` and add other custom header to all static assets, served by the `directory` handler.

The only solution, I found, was to set the headers using the `onPreResponse` hook, but this requires checking the if file path matches the  directory router.

Is there a better way to add/modify the headers for these handlers ?

**Comment by dupski** [comment]
For anyone finding this that just wants to change the `Cache-Control` header, you can simply use the `cache.expiresIn` config option in your Hapi route config, e.g.:

```js
server.route({
	method: 'GET',
	path: '/static/{param*}',
	handler: directoryHandler('static'),
	config: {
		cache: {
			expiresIn: 1000 * 60 * 60 * 24 * 7  // 7 Days in ms
		}
	} as any
});
```

For more info, see the options for `cache` in https://hapijs.com/api#route-options
