### ISSUE TITLE
Api routing not working when adding static folder path

### ISSUE THREAD

**Issue by SaurabhLpRocks** [hapijs/inert#110]
I've added static files folder "public" as a static path in my routes using directory handler as following as mentioned [here][1].

**src/server.ts:**

          server.connection({
                    port,
                    routes: {
                        cors: true,
                        files: {
                          relativeTo: Path.join(__dirname, 'public')
                      }
                    }
                });
        
    //Provide static path with directory handler
                  server.register(Inert);
                   server.route({
                     method: 'GET',
                     path: '/{param*}',
                     handler: {
                      directory: {
                        path: Path.join( __dirname, 'public'),
                        redirectToSlash: true,
                        listing: true,
                      },
                     },
                   });

**src/users/routes.ts:**

    server.route({
        method: '*',
        path: '/api/login',
        config: {
            auth: {
                strategy: 'azure-oidc',
                mode: 'try',
            },
            handler: userController.loginUser,
            tags: ['api', 'user'],
            description: 'Get user info.',
        },
    });

When I try to hit **http:localhost:5000/api/login** I get 404. 
But if I remove static path route from src/server.ts, I am able to hit http:localhost:5000/api/login route. 

Also, If I keep static path route in server.ts and change the path in it from '/{param*}' to '/' I get following error:

> unhandledRejection Error: The route path for a directory handler must
> end with a parameter: /

What I am doing wrong here?

  [1]: https://github.com/hapijs/inert

**Comment by kanongil** [comment]
Hapi matches the path before testing for the method.

Please direct usage questions to the [discuss](https://github.com/hapijs/discuss) repo.
