### ISSUE TITLE
Directory handler to allow downloading the entire directory in a zip?.

### ISSUE THREAD

**Issue by bhrgv-bolla** [hapijs/inert#117]

**Comment by Marsup** [comment]
I'd say this is out of the scope of this module.

**Comment by kanongil** [comment]
The specific request is indeed out of scope, but it might make sense to have a hook that allows you to implement this yourself (or in a new addon) based on the directory handler.

I believe the implementation in https://github.com/hapijs/inert/pull/90 could enable this for some use-cases. Eg. you could add a custom "listing" like this:

```js
const listing = async (request, context) => {

    if (request.query.zip) {
        return await myDirectoryZipper(context.path);
    }

    …
};
```

One caveat, is that it doesn't work if there is an index file.

**Comment by bhrgv-bolla** [comment]
Thanks for the thoughts!. I did this by generating a new zip and serving the zip file with inert reply.file().
