### ISSUE TITLE
Ability to serve directory inside route handler

### ISSUE THREAD

**Issue by CragVFX** [hapijs/inert#120]
I have a static content route that I use to serve a web application:

```
    await server.route({
      method: 'GET',
      path: '/{param*}',
      handler: {
        directory: {
          path: path.join(__dirname, '..', 'dist')
        }
      }
    });
```
And I have a 404 catchall check:

```
    server.ext('onPreResponse', (request, h) => {
      const response = request.response;
      if (response.isBoom && response.output.statusCode === 404) {
        /* I want to serve a custom 404 page here with image file(s)
         * h.file() only allows me to serve a single file
         * I want the ability to serve a directory here
         */
        return h.file(path.join(__dirname, '..', 'dist', '404.html')).code(404);
      }
      return h.continue;
    });
```
What I am struggling with is, serving static content that the 404 page utilizes, ie:
 
`<img src="/some/image/I/want/to/serve.png"/>`

but the h toolkit does not (from what I can find) have a way to serve a static file AND it's dependencies, if there was a way to do h.directory(path.join(__dirname, '..', '404Dir')).code(404)

Can anyone think of a way to serve more than 1 file via the h toolkit when handling 404s without hosting the referenced images elsewhere?

**Comment by CragVFX** [comment]
One solution I have is making a route for 404s ie /404/{param*} with directory handler via inert. 

Then inside the 'onPreReponse' event, I can use 

`return h.redirect('https://site/404/')`

**Comment by Marsup** [comment]
I'm not sure I understand the question, a 404 is usually a single file with links to other resources that are loaded in a separate query, you can't serve a full directory or even multiple files in one request, that doesn't make sense. Are the URLs you use in the 404 page actually valid?

**Comment by kanongil** [comment]
I think the issue, is dynamically returning a directory listing, along with access to listed files, outside a `directory` handler. This is not possible to do simply in a generic way.

Your redirect solution sounds like a reasonable way to solve this.
