### ISSUE TITLE
6.0.1 should be 7.0.0 because it required hapi 19 whereas 6.0.0 does not

### ISSUE THREAD

**Issue by alubbe** [hapijs/inert#141]
Hi,

when you released 6.0.1, our hapi 18 server can no longer start, as it crashes because inert suddenly wants hapi 19. It used to work with 6.0.0 - could you revert the upgrade for a 6.0.2 release and continue on 7.0.0?

Thanks!

**Comment by kanongil** [comment]
As far as I can see, the hapi 19 requirement was an oversight that was missed in the 6.0.0 release, which lasted for 1 week. It is unfortunate that you installed inert during that period.

I suggest you either downgrade to the v5 release line, or preferably upgrade hapi to v19.

**Comment by kanongil** [comment]
Oh, and _always_ ensure that your deployment dependencies are version locked to avoid these kind of issues in production.

**Comment by alubbe** [comment]
we'll downgrade back to v5 for now, since our hapi v19 upgrade is blocked by migrating our 300+ routes to the new `joi`, which as changed quite considerably. any tips on how to do that route by route or can it only be done in one chunk?

**Comment by hueniverse** [comment]
You can easily upgrade to hapi v19 and use the new `server.validator()` to lock it to joi v15.
