### ISSUE TITLE
@hapi/ammo - Denial of Service

### ISSUE THREAD

**Issue by chrc** [hapijs/inert#143]
#### Support plan
* *which support plan is this issue covered by?* Community
* *is this issue currently blocking your project?* no
* *is this issue affecting a production system?* no

#### Context

* *node version*: 12.14.1
* *module version*: 5.2.2
* *environment* (e.g. node, browser, native): node
* *used with* @hapi/ammo
* *any other relevant information*:

#### How can we help?
Reporting a general vulnerability from NPM advisories regarding Denial of Service from @hapi/ammo@3.1.1 use.

| High          | Denial of Service                 |
|---------------|-----------------------------------|
| Package       | @hapi/ammo                        |
| Dependency of | @hapi/inert                       |
| Path          | @hapi/inert > @hapi/ammo          |
| More info     | https://npmjs.com/advisories/1474 |

Would be great to have inert update as well to patch the vulnerability.

**Comment by hueniverse** [comment]
This module already uses the latest version of ammo with the patch. There is nothing to do.
