### ISSUE TITLE
EMFILE 'Failed to open file' error when hapi serves static files. hapi 8.4.0

### ISSUE THREAD

**Issue by Kyii** [hapijs/inert#24]
reopen from https://github.com/hapijs/hapi/issues/2507

Suddenly after weeks working on an application without any problems this error (below) - trying to serve my front-end main.js - comes up irregular but continuous. After restarting the server it's gone for a while, but comes up again.
 
I saw an old issue so maybe this is related to https://github.com/hapijs/hapi/issues/1387 ? 

But i don't fully understand. Is this error related to hapi, node or maybe my build process (gulp) ?

Thank you very much for your help. Or any hint how i can further investigate this error.

hapi: 8.4.0
node: 0.10.33
gulp: 3.8.11
OSX: 10.9.5 
Chrome: 42.0.2311.90
    
    Debug: handler, error
    {
    "msec":0.32216699980199337,
    "error":"Failed to open file: EMFILE, open 'static/main.js'",
    "data": {
        "errno":20,
        "code":"EMFILE",
        "path":"static/main.js",
        "isBoom":true,"data":null,
        "output": {
            "statusCode":500,
            "payload":{
                "statusCode":500,
                "error":"Internal Server Error",
                "message":"An internal server error occurred"},
                "headers":{}
    }}}
    
    150418/083817.200, [error], message: Failed to open file: EMFILE, open 'static/main.js' 
    stack: Error: Failed to open file: EMFILE, open 'static/main.js'
    

this is my static route inside a plugin:

    server.route({
            path: '/static/{file*}',
            method: 'GET',
            config: {
                auth: false
            },
            handler: {
                directory: {
                    path: './static',
                    listing: false,
                    index: false
                }
            }
        });

my impression is that the errors are present after rebuilding static files with gulp and then reloading the server. 

thanks.

**Comment by kanongil** [comment]
If you apply the route as described to a plain server, you should not receive `EMFILE` errors unless you are experiencing heavy traffic.

I suspect your issue is caused by one of your `onPostHandler` or `onPreResponse` handlers that forgets to call one of the `reply´ methods. Note that any plugin can register these handlers as well.

**Comment by Kyii** [comment]
thank you very much!
i am not using onPostHandler or onPreResponse handlers. but recently i introduced the usage of a few different Route prerequisites "pre" for handling ACL business logic. 
could this be related too? 
in the meantime even more static file errors are appearing. i guess will look at those ACL functions again. 
    
    150420/132323.837, [error], message: Failed to read view file: server/web/index.html stack: Error: Failed to read view file: server/web/index.html
    at Object.exports.create (/Users/john/dev/hapi/doe/node_modules/hapi/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/john/dev/hapi/doe/node_modules/hapi/node_modules/boom/lib/index.js:252:92)
    at Object.exports.badImplementation (/Users/john/dev/hapi/doe/node_modules/hapi/node_modules/boom/lib/index.js:288:23)
    at /Users/john/dev/hapi/doe/node_modules/hapi/node_modules/vision/lib/manager.js:452:34
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)

    Debug: internal, implementation, error
    Error: Failed to read view file: server/web/index.html
    at Object.exports.create (/Users/john/dev/hapi/doe/node_modules/hapi/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/john/dev/hapi/doe/node_modules/hapi/node_modules/boom/lib/index.js:252:92)
    at Object.exports.badImplementation (/Users/john/dev/hapi/doe/node_modules/hapi/node_modules/boom/lib/index.js:288:23)
    at /Users/john/dev/hapi/doe/node_modules/hapi/node_modules/vision/lib/manager.js:452:34
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)

**Comment by kanongil** [comment]
If you have an earlier check-in version which is known to work, `git bisect` is an awesome tool to figure out which commit introduced the error.

Also note that non-closed file descriptors could be caused by any filesystem usage in your server. You can use the `lsof` tool on an active process to inspect which descriptors are actually open. This should give you a much clearer insight into which part of the server is the real culprit.

**Comment by Kyii** [comment]
thanks again for your kind tips and suggestions kanongil. they helped a lot. in the end it was a filesystem error caused by gulp watch. shot.
