### ISSUE TITLE
Adding custom headers with the directory handler

### ISSUE THREAD

**Issue by moret** [hapijs/inert#39]
Hello guys. I have a question: is there any way to use the directory handler and add some custom headers? I'm trying to combine the convenience of the directory handler guarding from malevolent input and still being able to add some fixed headers to the files. Something like:

````javascript
server.route({
  method: 'GET',
  path: '/static/{data*}',
  handler: {
    directory: {
      index: false,
      path: 'static/data/',
      customHeaders: [
        {name: 'X-Some-Custom-Header', value: 'someCustomValue'},
        {name: 'X-Another-Custom-Header', value: 'anotherCustomValue'}
      ]
    }
  }
});
````

**Comment by kanongil** [comment]
The best way to go about this is to use the `onPreResponse` extension hook and `app` config option. Eg something like:

```js
server.route({
  …
  config: {
    app: {
      customHeaders: {
        'x-my-custom-header': 'awesome'
      }
    }
  }
});

server.ext('onPreResponse', function (request, reply) {

  var response = request.response;

  if (request.response.variety === 'file') {
    var customHeaders = request.route.settings.app.customHeaders || {};
    for (var header in customHeaders) {
      response.header(header, customHeaders[header]);
    }
  }

  reply.continue();
});
```

Sorry for the slow response, but this is not really the best forum for such questions. https://github.com/hapijs/discuss is much better suited.

**Comment by moret** [comment]
Sorry about not using the discuss project. And thank you for the reply! :smile:
