### ISSUE TITLE
Add new attributes: connections: false, once: true

### ISSUE THREAD

**Issue by hueniverse** [hapijs/inert#43]
This will allow hapi >= 10.2 to know the plugin is available to connections added after it was registered. It is backwards compatible.

**Comment by kanongil** [comment]
The `once: true` attribute is not compatible with `hapi@10.3.0`, and thus not fully backwards compatible. Is this intended?

**Comment by hueniverse** [comment]
Wait until 10.4 is published to push.

**Comment by kanongil** [comment]
New version published as 3.1.0.

**Comment by hueniverse** [comment]
Nice. This will allow people to always just register it and not care if it is already there.
