### ISSUE TITLE
Failed to open file: EMFILE

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/inert#45]
I just got
```js
Debug: internal, implementation, error 
     Error: Failed to open file: EMFILE, open '/home/***/src/assets/img/image.gif'
```
together with
```js 
Error: EMFILE, too many open files
     at /home/***/node_modules/good/lib/utils.js:24:26
```
I serve the img with `reply.file()`.
Some googling told me to many files were open but not sure how to solve this.

**Comment by kanongil** [comment]
`EMFILE` errors means that the system has run out of file descriptors, needed to open new files. This can potentially be caused by a problem with `Inert`, but it is also possible other modules / processes are draining these by forgetting to close files.

This problem is best debugged using the `lsof` command line tool, used while this is happening.

Also, which versions are you using? Which system? And are there any specific conditions which trigger this behavior?

**Comment by mtharrison** [comment]
You can increase your open file descriptor limit. There's a couple of explanations here: 

http://stackoverflow.com/questions/21515463/how-to-increase-maximum-file-open-limit-ulimit-in-ubuntu
http://stackoverflow.com/questions/21515463/how-to-increase-maximum-file-open-limit-ulimit-in-ubuntu

Also worth checking that you really need to raise the limit and it's not just that you're leaking files somehow:

lsof -p $PID

**Comment by AdriVanHoudt** [comment]
It is not even showing the file in `lsof` so it is definitely not leaking. Could be higher load not sure, I have seen higher loads handled fine.
I am using Debian and Inert 3.0.1 atm.
Maybe something with Good?

**Comment by mtharrison** [comment]
I didn't mean that Inert specifically was leaking files, could have been something else in your app that was opening files and not closing them. The default limits aren't particularly high though ,could be you just need to increase them.

**Comment by AdriVanHoudt** [comment]
Ah you mean any process doing it and then my server throws, fun.
Is this common? I mean the load wasn't that high and nothing else runs on the server and this is the first time I've seen it, weird.

**Comment by kanongil** [comment]
> It is not even showing the file in lsof so it is definitely not leaking.

All open files by any process owned by the same user can cause this. Try `lsof -u <process user>`.

**Comment by AdriVanHoudt** [comment]
Not sure what to fill in into `<process user>` and it didn't show up under the node process

**Comment by kanongil** [comment]
`<process user>` should be the user id for the user that node process runs under, which will depend on your deployment method.

You can also just run `lsof` to get an unfiltered list.

**Comment by AdriVanHoudt** [comment]
yeah can't find it in there, will close for now and come back with more debug info when this happens again, thanks for the info!

**Comment by mrose17** [comment]
@AdriVanHoudt & others - in my experience, the most likely cause for an EMFILE when using inert is having a `server.ext('...', (request, reply) => { ... })` that does not `return reply.continue()` as this prevents inert from closing the file object during cleanup.
