### ISSUE TITLE
ES6 style changes and node v4

### ISSUE THREAD

**Issue by hueniverse** [hapijs/inert#49]
Apply the latest ES6 hapi style:
- use strict
- `const` and `let` where appropriate (linter will tell you where)
- arrow functions where appropriate (linter will tell you where)
- relevant updates to tests + docs
- updating deps and engine in package.json
- avoid `self` and `+=` / `-=` (not optimized yet for let const)
- change .travis to test 4.0, 4, and 5

**Comment by kanongil** [comment]
I plan to make a pass at this but currently waiting on #47.

**Comment by kanongil** [comment]
Closed via cbab9fc06a7ce7218a81cf2e34b8c0717792824e & ef243e18022e303c1a298ba84a024a0a2a448af3.
