### ISSUE TITLE
lookupCompressed flag does not work on directory

### ISSUE THREAD

**Issue by geekgirl911** [hapijs/inert#52]
I have the following directory setup for public folders

        {
            method: "GET",
            path: "/assets/{path*}",
            config: {
                description: 'Serve static content from public folder with director listing',
                handler: {
                    directory: {
                        path: "public",
                        lookupCompressed: true
                    }
                },
                tags: ['assets']
            }
        },

in the folders I have the following files:

client-2.0.0.min.css         - size: (97,959)
client-2.0.0.min.css.gz    - size: (36,210)
vendor-3.0.0.min.css      - size: (148,214)
vendor-3.0.0.min.css.gz - size: (24,153)

When I request the asset it should serve back with the gzipped file, the response header should contain: content-encoding': 'gzip'
but nothing. I tried to trace it in the library and I checked the file.js properly looks for the gz file and sets the header info but it all get lost in the directory callback and revert back to serve the min.js file. 

I tried to delete the min.js files to "force" to serve back the gz files but then just fails with file not found.

**Comment by kanongil** [comment]
The response will only contain the gzipped file if the request has specified that gzip is ok using the `accept-encoding` header. Is this the case?

**Comment by geekgirl911** [comment]
Request headers does have the accept-encoding header with the values of: 'gzip, deflate, sdch'
![image](https://cloud.githubusercontent.com/assets/3298517/11983011/fe2c7e70-a964-11e5-9a31-c934b54ecda1.png)

**Comment by geekgirl911** [comment]
![image](https://cloud.githubusercontent.com/assets/3298517/11983098/afb76bfa-a965-11e5-866a-55251df93b08.png)

**Comment by kanongil** [comment]
Well that sounds like a bug. Unfortunately I am unable to replicate it.

Which versions of node, hapi & inert are you using?

Are you using any specific `server` or `connection` options? Or registering other plugins?

**Comment by kanongil** [comment]
Actually, given that you are on Windows, this issue is likely caused by your anti-virus software, which will have modified the response before serving it to the browser.

Can you disable any such software and test again?

**Comment by geekgirl911** [comment]
Versions:
node: 5.0.0
inert: 3.2.0
hapi: 11.1.2
I added console.log(...) into this part of the code: (internals.marshal)
        response.bytes(stat.size);
        response.header('content-encoding', 'gzip');
        response.vary('accept-encoding');
        console.log(response.headers);
        return internals.openStream(response, gzFile, next);

![image](https://cloud.githubusercontent.com/assets/3298517/11986939/44cabc36-a98b-11e5-9495-98a7af43e46d.png)

Then I added a console.log to the onPreResponse event

server.ext('onPreResponse', function (request, reply) {
    console.log(request.response.headers);
    return reply.continue();
});

![image](https://cloud.githubusercontent.com/assets/3298517/11987056/42627e1e-a98d-11e5-9fb2-9e7f515acd74.png)

It shows what I am seeing in the browser. I disabled my anti-virus but I do not really see how can cause anything while the code running inside hapi framework.

**Comment by kanongil** [comment]
The `onPreResponse` is as intended – The marshal phase happens after the `onPreResponse` hook, and before it knows that there exists a gzipped version of the file.

I still think the culprit is some local firewall (or maybe a chrome extension), which modifies the response.

**Comment by geekgirl911** [comment]
I am running the app locally and I tried with Firefox + Firebug with the same result.

**Comment by geekgirl911** [comment]
Bypassed problem by replacing the single directory handler with 3 handlers specialized for each type and with the file handler the compression works in the same environment. From my point of view I "resolved" the issue but I think it is still a bug so I keep this open.
```javascript
    server.route([
        {
            method: "GET",
            path: "/styles/{filename}",
            config: {
                description: "Serve css styles",
                handler: function (request, reply) {
                    reply.file(path.join('public/css', request.params.filename), { lookupCompressed: true });
                },
                tags: ['assets']
            }
        },
        {
            method: "GET",
            path: "/scripts/{filename}",
            config: {
                description: "Serve js scripts",
                handler: function (request, reply) {
                    reply.file(path.join('public/js', request.params.filename), { lookupCompressed: true });
                },
                tags: ['assets']
            }
        },
        {
            method: "GET",
            path: "/images/{filename}",
            config: {
                description: "Serve images",
                handler: function (request, reply) {
                    reply.file(path.join('public/img', request.params.filename));
                },
                tags: ['assets']
            }
        },
```

**Comment by kanongil** [comment]
There is no such hook. If you want to check the headers, as it it passed onto node itself, you can grab them in hapi itself here: https://github.com/hapijs/hapi/blob/v11.1.4/lib/transmit.js#L286.

**Comment by kanongil** [comment]
Also, please don't use the `reply.file()` without parameter validate. The ones you linked can allow access to any file on your server.

**Comment by geekgirl911** [comment]
Thanks for pointing me to the hapi.js line. It was very useful. It seems like the proper size and header information set with the expected gzip-ed result. I think you right, it might be caused by something else. (OS or anti-virus software) I will be setting up a virtual box with Linux and checking it again. As for the validation of course I will have it setup. This was just a quick way to check the results. Thanks for noting though! :)
