### ISSUE TITLE
Cannot read property 'lookupCompressed' of undefined

### ISSUE THREAD

**Issue by lynnaloo** [hapijs/inert#54]
Using Hapi v11.1.4, I'm getting this error here `/lib/file.js:110:34` when I'm using `reply.file`. This is what my sample code looks like:

server.route({
        method: 'GET',
        path: '/users/{userName}/image',
        handler: function (request, reply) {
            reply.file('/full/path/to/image.png');
        }
    });

I also tried sending in an `options` object and setting all of the values as well.

**Comment by lynnaloo** [comment]
This was happening due to some other code in my project. Closing :grinning:

**Comment by wsaleme** [comment]
What was your code issue? I'm having the same "problem"

**Comment by lynnaloo** [comment]
I can't quite remember, but I think it's possible that the plugin wasn't loading.
