### ISSUE TITLE
"The route path must end with a parameter"

### ISSUE THREAD

**Issue by prashaantt** [hapijs/inert#55]
The following route fails hard at [this line](https://github.com/hapijs/inert/blob/master/lib/directory.js#L34):

```js
server.route({
    path: '/favicon.ico',
    method: 'GET',
    handler: {
        directory: {
            path: 'public'
        }
    }
});
```

The [tutorial](http://hapijs.com/tutorials/routing#user-content-multi-segment-parameters) says it's allowed (and preferred over ```/favicon.{ext}``` — which of course does work).

I don't know enough yet but I think all routing rules ought to be deferred to hapi core.

**Comment by johnbrett** [comment]
Ah this is an easy one to mistake, if you're using the directory handler, it should be serving a range of files. If you're serving an actual file, use the file handler. 

The issue here is the custom handler,  not the routing.

**Comment by prashaantt** [comment]
Ah, that makes total sense, and I just found it in the docs too. Sorry for the bother.

**Comment by anzileiro** [comment]
Look at the example routes for static files on github own website http://hapijs.com/

https://github.com/hapijs/hapijs.com/blob/master/lib/routes.js

**Comment by iamnena** [comment]
change 
path: '/favicon.ico', to

**Comment by iamnena** [comment]
path: '/{param*}',
