### ISSUE TITLE
Content-Type header based on filename option

### ISSUE THREAD

**Issue by amincheloh** [hapijs/inert#57]
Hello,

I would like inert set Content-Type header based on filename option instead of path filename.

for usage example

``` javascript
reply.file(doc.fullPath, {
    filename: doc.name,
    mimeFromFilename: true
});
```

for current my workaround in [lib/file.js](../tree/master/lib/file.js)

``` javascript
        if (!response.headers['content-type']) {
            var mimePath;
            if (response.source.settings.mimeFromFilename) {
                mimePath = response.source.settings.filename;
            } else {
                mimePath = path;
            }
            response.type(response.request.server.mime.path(mimePath).type || 'application/octet-stream');
        }
```

Thanks

**Comment by kanongil** [comment]
I don't think it is useful to add such an option, though I might consider always using `filename` when available to determine the mime type.

For `reply.file()` you should be able to use the standard hapi response methods to customize the returned mime type. Eg.:

```js
reply.file(doc.fullPath, {
    filename: doc.name
}).type(request.server.mime.path(doc.name).type || 'application/octet-stream');
```
