### ISSUE TITLE
Is it possible to use Inert with Handlebars (Vision)?

### ISSUE THREAD

**Issue by mrmartineau** [hapijs/inert#58]
I am extremely new to hapi and I am hoping to create a simple prototyping framework using it. I would like to use Handlebars for templating (which means using Vision), is it possible to also use inert to serve the files? Is it possible for the routes be determined from the handlebars view files?

**Comment by mtharrison** [comment]
Inert is just for serving static files as-is, you can serve any files you like. Normally though you'd want to compile a Handlebars template (along with a context) and serve that as HTML. Which is exactly what vision does.

**Comment by mrmartineau** [comment]
Ok, thank you for the explanation. I am basically trying to get dynamic routing whilst also using Handlebars templates.. I will investigate Vision in more detail.

**Comment by mtharrison** [comment]
I think you could use a parametrized route for that:

```javascript
server.route({
    method: 'GET',
    path: '/view/{name}',
    handler: function (request, reply) {

        return reply.view(request.params.name);
    }
}); 
```

Careful with things like that though, you'll want to make sure you don't allow absolute paths or insecure access.

**Comment by mrmartineau** [comment]
Thanks for your advice @mtharrison, I'll look into your suggestion.
