### ISSUE TITLE
Support brotli compression

### ISSUE THREAD

**Issue by nrotta** [hapijs/inert#64]
Hi.

I'm working on adding brotli support for Hapi as requested in https://github.com/hapijs/hapi/issues/3037

I made the required changes on my Hapi, Inert, and Subtext forks and added the required tests. All tests are passing in Hapi and Subtext but I still have one failing test in Inert.

You can see all the changes in my forks but the failing test code is the following:

```
it('returns a subset of a file using br precompressed file', (done) => {

    const server = provisionServer();
    server.route({ method: 'GET', path: '/file', handler: { file: { path: Path.join(__dirname, 'file/image.png'), lookupCompressed: true } } });
    server.inject({ url: '/file', headers: { 'range': 'bytes=10-18', 'accept-encoding': 'br' } }, (res) => {

        expect(res.statusCode).to.equal(206);
        expect(res.headers['content-encoding']).to.equal('br');
        expect(res.headers['content-length']).to.equal(9);
        expect(res.headers['content-range']).to.equal('bytes 10-18/41978');
        expect(res.headers['accept-ranges']).to.equal('bytes');
        expect(res.payload).to.equal('image.png');
        done();
    });
});
```
It is the same test that is used to test gzip compression but with the small changes required to test brotli compression.

It fails in the following line:
```
expect(res.payload).to.equal('image.png');
```
The res.payload returns "\u0019�Q�".

After a lot of work, I'm still not able to find what the issue is. I was wondering if someone could point me in the right direction.

I also noticed that there is a open issue that could be related (although I guess the test should pass independently of the proposed feature). I'm referring to https://github.com/hapijs/hapi/issues/3133

Thanks,
Nicolas

**Comment by kanongil** [comment]
It just compares some bytes from the pre-encoded file to check that it is transferred correctly. In my case I chose bytes `10-18` that happens to contains the file name in the gzip file.

Btw, if you need to compare non-string values, you should use the `Buffer` from `rawPayload` instead.

**Comment by nrotta** [comment]
Thanks for the really quick response.

I compared the ```Buffer``` returned from ```rawPayload``` for bytes ```10-18``` against a Buffer from the already compressed file for the same bytes. This way I can ensure that the file was transferred correctly.

It works like a charm. I will close the issue and send a PR.

Thanks for your help.
