### ISSUE TITLE
Inert unable to serve my .css file

### ISSUE THREAD

**Issue by eakl** [hapijs/inert#66]
Hi,

I'm unable to serve a css file using Inert and Vision.

I have an issue to serve my `app.css` file in the `default.html` view using hapijs/Inert/Vision. I use Cloud9 for hosting but it shouldn't be a problem.

Here is my app structure

```
app/
   client/
      config/
         route.js
      css/
         app.css
      view/
         layout/
            default.html
         index.html
server.js
```

My server.js

```javascript
'use strict';

const Hapi      = require('hapi');
const Vision    = require('vision');
const Inert     = require('inert');
const Path      = require('path');
const Routes    = require('./client/config/route')

const server = new Hapi.Server();

server.connection({
    host: process.env.IP || '0.0.0.0',
    port: process.env.PORT || 3000
});

server.register([Vision, Inert], (err) => {
    if (err) {
        throw err;
    }

    server.views({
        engines: {
            html: require('handlebars')
        },
        relativeTo: Path.join(__dirname, 'client'),
        path: 'views',
        layoutPath: 'views/layouts',
        layout: 'default', // true
        partialsPath: 'views/partials'
    });

    server.route(Routes);
});

server.start(() => {
    console.log('Server started at: ' + server.info.uri);
});
```

My route.js

```javascript
const Path  = require('path');

const routes = [
    {
        method: 'GET',
        path: '/{param*}',
        handler: {
            directory: {
                path: Path.join(__dirname, 'client'),
                listing: false,
                index: false
            }
        }
    },
    {
        method: 'GET',
        path: '/',
        handler: (req, rep) => {

            let data = { };                
            rep.view('index', data);
        }
    }
];

module.exports = routes;
```

My default.html using handlebars

```html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Title</title>
        <link rel="stylesheet" href="../../css/app.css" />
    </head>
    <body>
        {{{content}}}
    </body>
</html>
```

My index.html

```html
<p id="paragraph">Hello World<p>
```

The issue is that my `app.css` doesn't load. I have followed [this advice](https://github.com/hapijs/hapi/issues/1539) and [this one](http://stackoverflow.com/questions/23852020/hapi-js-views-not-seeing-local-scripts?answertab=votes) but it still doesn't work and I don't know what to check next. Is something wrong with Inert plugin or am I doing something wrong?

**Comment by Marsup** [comment]
Why would your css be in `../../` ? You're serving `client` as root.

**Comment by eakl** [comment]
I tried different path, even `./css/app.css` doesn't work.

I tried from `client/`, from `/`, from `views/` and from `layouts/`

**Comment by Marsup** [comment]
Remove those dots in your html, inert doesn't seem to be the problem here.

**Comment by kanongil** [comment]
This is not a problem with inert. If you have problems using hapi, etc, I suggest you direct questions to [hapijs/discuss](https://github.com/hapijs/discuss).
