### ISSUE TITLE
Use reply.entity() early to set known etag and last-modified

### ISSUE THREAD

**Issue by hueniverse** [hapijs/inert#69]

**Comment by kanongil** [comment]
I already looked into this and couldn't find a nice way to implement it, and decided to scrap since it is s breaking change without any obvious benefit.

If you have any specific implementation ideas, please let me know.

**Comment by hueniverse** [comment]
I think for a server serving a lot of static file, this could be meaningful because it will skip opening all the 304 file streams, just to close them back unused. I haven't looked at this code so I don't know how hard it would be, but I can't imagine setting the etag header early is hard when it's already available.

**Comment by kanongil** [comment]
I currently always open the file to ensure it is still there and obtain fstat info. Depending on the etag mode, I need this to either directly calculate the etag, or for a cache lookup.

An actual file stream is only created (based on the already open `fd`) in the marshaling phase, which is skipped for 304 responses.

**Comment by hueniverse** [comment]
This is your decision. I don't use inert myself...
