### ISSUE TITLE
Is it possible to apply templating to files returned via a directory handler?

### ISSUE THREAD

**Issue by ekawas-de** [hapijs/inert#72]
I have a directory handler returning files in a specific directory, but some of the files are view templates and I was wondering if there was a way to use the directory handler and render the template.

**Comment by devinivy** [comment]
You'll want to use [vision](https://github.com/hapijs/vision) rather than inert for that.  If you have a mix of templates and static files for some reason, you might want to write a handler that calls `reply.file()` or `reply.view()` depending on which is more appropriate.

**Comment by marcuspoehls** [comment]
Hey @ekawas-de, to have templating support within your view files, you should render them using [vision](https://github.com/hapijs/vision) and apply the file handling with the help of [inert](https://github.com/hapijs/inert). 

If you need more details on how to integrate both into your hapi project, those tutorials will help you:

- https://futurestud.io/tutorials/hapi-how-to-render-views
- https://futurestud.io/tutorials/hapi-how-to-serve-static-files-images-js-etc

Hope that helps!
