### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by hueniverse** [hapijs/inert#76]

**Comment by kanongil** [comment]
@hueniverse How do we handle the subtle `.boolean()` breakage in the Joi schemas? There is a chance that someone relies on it handling eg `"false"`, and the update breaks their existing install as it is.

**Comment by kanongil** [comment]
Oh, you already published this as a patch release. Guess we just wait and see then..

**Comment by hueniverse** [comment]
I'm not too worried about it and it will block the process from starting so it's an easy fix.
