### ISSUE TITLE
lookupCompressed not working as I expected

### ISSUE THREAD

**Issue by sebasgarcep** [hapijs/inert#77]
I have a bunch of javascript files I'm serving with Inert. To reduce their file size I gzipped them and erased the uncompressed versions, but when trying to serve them I get a 404 error. When the uncompressed files are present there are no issues.

I expect Inert to serve the compressed version of the files without needing the uncompressed to be right there next to it. Is there something wrong with these assumptions?

Thanks.

**Comment by kanongil** [comment]
Inert will only lookup a compressed version of an existing file. It needs this, since clients can request both versions.
