### ISSUE TITLE
Unable to download file as an attachment

### ISSUE THREAD

**Issue by prakharsingh** [hapijs/inert#84]
Hapi version: 16.0.0
Inert version: 4.0.1

```
const fileName = 'whatever.txt';
const filePath = `${os.tmpdir()}/${fileName}`;

fs.writeFile(filePath, 'some_random_text', function(err) {
     if (err) return reply(Boom.internal(err));
     reply.file(filePath, {confine: false, filename: fileName, mode: 'attachment'});
});
```

The file gets rendered instead of being downloaded. Am I missing something here?
Thanks. #

**Comment by kanongil** [comment]
Please direct usage questions to the [discuss](https://github.com/hapijs/discuss) repo.

**Comment by prakharsingh** [comment]
@kanongil Thanks. Moved to [https://github.com/hapijs/discuss/issues/454](url)
