### ISSUE TITLE
reply.file() with relative paths doesn't work on Windows hosts

### ISSUE THREAD

**Issue by dcominottim** [hapijs/inert#85]
With a directory structure equivalent to

- projectRoot
    - lib
        *.js
    - public
        - img
            - commercial_entities
                - 1
                    0.jpg

and considering the following pertinent code placed in projectRoot/lib of a Windows host

```
const server = new Hapi.Server({
    debug      : {
        request: ['error']
    },
    connections: {
        routes: {
            files: {
                relativeTo: Path.join(__dirname, "..", 'public')
            }
        }
    }
});

server.connection({
    port: 3001
});

server.register(
    Inert, () => {
    }
);

server.register(
    require('hapi-auth-jwt'), (err) => {
        if (err) {
            throw err;
        }

        server.auth.strategy('token', 'jwt', {
            key          : Auth.jwtSecret,
            verifyOptions: {
                algorithms: ['HS256']
            }
        });
    }
);

server.start((err) => {
    if (err) {
        throw err;
    }

    console.log('Server running at: ', server.info.uri);
});

server.route(Router.routes);
```

```
exports.routes = internals.routes = [
    {
        method : 'GET',
        path   : '/images/commercial_entities/{entityId}/{param*}',
        handler: Query.getCommercialEntityImage
    }
];
```

```
exports.getCommercialEntityImage = internals.getCommercialEntityImage = function (request, reply) {
    reply.file(Path.join('img/commercial_entities/', encodeURIComponent(request.params.entityId), '/0.jpg'));
};
```

the file path is never resolved and the following error is printed on the console when the route is accessed

```
Debug: handler, error
    {"msec":3.9226608276367188,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{}},"message":"Not Found"}}
```

Please note that the same code runs fine on Linux hosts.

**Comment by Marsup** [comment]
Have you tried reversing the slashes to respect windows format ? You should be using `Path.join` fully if you want to be cross platform, not halfway like this.

**Comment by dcominottim** [comment]
@Marsup Do you mean reverse slashes as in the following snippet?

`reply.file(Path.join('img\\commercial_entities\\...`

**Comment by Marsup** [comment]
I mean you actually should be doing :
```js
Path.join('img', 'commercial_entities', encodeURIComponent(request.params.entityId), '0.jpg')
```
I'm not even sure what this `encodeURIComponent is doing there.

**Comment by dcominottim** [comment]
Good point about `encodeURIComponent` -- I don't know why it was there in this case.

Anyway, your proposed solution produces the same error. Additionally, `Path.join` seems smart enough to understand the '/' slashes of the original code, since the following snippet produces the same output with proper Windows reverse slashes for each console.log() call:

```
 console.log(Path.join(__dirname, '..', 'public', 'img', 'commercial_entities', request.params.entityId, '0.jpg'));
 console.log(Path.join(__dirname, '..', 'public', 'img/commercial_entities/', request.params.entityId, '0.jpg'));
```

```
D:\repo\project\public\img\commercial_entities\1\0.jpg
D:\repo\project\public\img\commercial_entities\1\0.jpg
```

**Comment by kanongil** [comment]
Can you provide a reduced test case that replicates this issue?

**Comment by kanongil** [comment]
Since I haven't heard more, I'm going to close this again, assuming it was an application error. Feel free to re-open if you don't think it has been resolved.
