### ISSUE TITLE
Question regarding type of error returned by path function of the directory handler

### ISSUE THREAD

**Issue by AJamesPhillips** [hapijs/inert#88]
Hi thanks for the great library.

I'm updating the types to 4.2 and just wanted to check I understood the statement in the docs about the path option of the directory handler: "If the function returns an error, the error is passed back to the client in the response.".  I guess it can return a BoomError or a node.Error (that will be converted into a BoomError?).  (And that it should not throw this error, I know the docs say return I just wanted to double check).

Thanks!

https://github.com/AJamesPhillips/DefinitelyTyped/blob/8cc992680/types/inert/index.d.ts#L45

**Comment by kanongil** [comment]
It will just do a `reply(err)`.

I guess you could also throw an error, though I would advise against this, as it is not a documented or tested behaviour.

In the future please direct usage questions to the [discuss](https://github.com/hapijs/discuss) repo.
