### ISSUE TITLE
 cache into memory

### ISSUE THREAD

**Issue by elf-pavlik** [hapijs/inert#91]
https://www.npmjs.com/package/connect-static
> When you create the middleware, it will immediately scan the requested directory, gzip all the files, and save the cache into memory, where it will forever remain. When a request hits the middleware it never touches the file system.

In a similar way, I would like to specify per `directory` handler to cache files in memory or not.

**Comment by kanongil** [comment]
Thanks for the input.

Caching certainly has it place in serving static files. Usually this is done in a reverse proxy / CDN, and I don't see the need to complicate the implementation in Inert to also handle this.
