### ISSUE TITLE
Cannot set a default route after static assets check with the directory handler

### ISSUE THREAD

**Issue by acmoune** [hapijs/inert#95]
Using the directory handler, I can do this:

```javascript
server.route({
    method: 'GET',
    path: '/{params*}',
    handler: {
      directory: {
        path: path.resolve(__dirname, 'assets')
      }
    }
  })
```
This will try to map all unmatched URI to files in the `assets` directory. 

I want to keep this facility, but I am trying to perform server rendering for a React app, so I need that same pattern ('/{params*}') to respond to all request with the same index view, and deal with the actual URI in the React router. 

How can I set a default route twice ? one for static assets, and the other for anything else ?

With Express you can achieve this by first including the express.static middleware:

```javascript
const app = express()
const fileAssets = express.static(path.resolve(__dirname, 'assets'))  // default for static assets
const respond = (req, res) => {...}  // default for anything else
app.use(fileAssets).use(respond)
```
How can I achieve this with Hapi and Inert plugin ?

Thanks in advance.

**Comment by kanongil** [comment]
Please direct usage questions to the [discuss](https://github.com/hapijs/discuss) repo.

**Comment by acmoune** [comment]
Ok

**Comment by acmoune** [comment]
https://github.com/hapijs/discuss/issues/541
