### ISSUE TITLE
Promise support for directory path

### ISSUE THREAD

**Issue by sstawecki** [hapijs/inert#96]
Hi, I'm trying to do something like this

>         {
>           method: 'GET',
>           path: '/l/{path*}',
>           handler: {
>             directory: {
>               path: (req) => {
>                 const defaultDir = '/public';
>                 return getHostInfo(req.headers.host).then((d) => {
>                   if (!d || !d.directory) return defaultDir;
>                   return d.directory;
>                 }).catch((e) => {
>                   return defaultDir;
>                 });
>               }
>             }
>           }
>         },

`path` parameter expects a string, array or function which returns a string or array...in my case, my function returns a promise...so it doesn't work.
Is there any chance to make it work? I tried adding `hapi-as-promised` package which modifies reply function to support `then` method but did't work.
Thanks in advanced and sorry if I'm wrong posting this issue here.

**Comment by kanongil** [comment]
The `function()` interface for the `path` option requires a normal return value. There is no async support, so it will never work.

If you can give a good explanation for why you _need_ to do an async lookup for the path, I will consider a PR to add async support.

If you want input on how to rework your code, to work without the promise, you can try posting to the [discuss](https://github.com/hapijs/discuss) repo.

**Comment by peterbee** [comment]
I am also interested in async support.  Here is my use case:
- My Hapi server supports multiple app versions
- App version is specified in each request
- Static asset directory is based on the app version requested
- If the requested app version does not exist on the current server instance, it is downloaded asynchronously

Because the static directory path may not exist at the time of the request, it would be excellent if the directory handler could accept a Promise as well.

**Current route config:**
```js
  {
    method: 'GET',
    path: '/public/{appVersion}/{filepath*}',
    handler: {
      directory: {
        // does not exist if appVersion has not been downloaded to this server yet
        path: request => `${appLoader(appVersion).path}/public`
      }
    }
  }
```

**Proposed route config:**
```js
  {
    method: 'GET',
    path: '/public/{appVersion}/{filepath*}',
    handler: {
      directory: {
        // async support waits for appLoader to download app before resolving directory path
        path: request => appLoader(appVersion)
          .then(app => `${app.path}/public`)
      }
    }
  }
```

**Comment by kanongil** [comment]
Thanks for the thorough explanation. Unfortunately a user side solution to this issue was not included in this issue. I suggest you use a `pre` handler to determine the path async, and use the assigned property in the lookup.
