### ISSUE TITLE
Revise etags caching mechanism

### ISSUE THREAD

**Issue by kanongil** [hapijs/inert#99]
There are 2 issues concerning the etag cache:

First, the `etagsCacheMaxSize` registration option is not compatible with `once` plugins, so the `etagsCacheMaxSize` needs to be moved somewhere else.

Second, since the removal of connections support means that multiple servers are likely to be created, the cache itself should be instantiated and used across multiple registrations.

The best solution I can seem to think of, is instantiating the plugin directly before registering it. Eg something like this:

```js
const Hapi = require('hapi');
const Inert = require('inert');

const server1 = Hapi.server();
const server2 = Hapi.server();

const sharedInert = new Inert({ etagsCacheMaxSize: 500 });

server1.register(sharedInert);
server2.register(sharedInert);
```

@hueniverse Any thoughts on this?

**Comment by kanongil** [comment]
Maybe hapi can be changed to require plugins to be instantiated with whatever options it needs, which will avoid the multiple registration options confusion?

**Comment by hueniverse** [comment]
I think you are over thinking this. In practice, what's the harm here? And if it really a common use case to have multiple connections all serving files from the same source?
